In [22]:
# Print all the variables, not only the last one
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [21]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt  #导入集成的pyplot
%matplotlib inline

import matplotlib.mlab as mlab

In [23]:
s = pd.Series([-1.111,2.228])

df = pd.DataFrame(data=[[-1.111,2.228],[24.7808,-3.812]],columns=['A','B'])

#### Set precision

In [4]:
np.set_printoptions(precision=4) # 设置之后显示的精确度

round(df,2)  # 设置单变量的精确度

np.around(np.random.rand(5, 5)*100)  # 设置单变量的精确度

#### Data Generation 

In [5]:
np.arange(4,10,2)   # arange的使用同range   lower : upper : step

np.linspace(-10,10,10)  # StartNum, EndNum, How many middle numbers

np.linspace(-np.pi,np.pi)   # Default as 50

np.logspace(0, 2, 20)  # logspace函数和linspace类似，不过它创建等比数列，下面的例子产生1(10^0)到100(10^2)、有20个元素的等比数列:

array([-10.    ,  -7.7778,  -5.5556,  -3.3333,  -1.1111,   1.1111,
         3.3333,   5.5556,   7.7778,  10.    ])

array([-3.1416, -3.0134, -2.8851, -2.7569, -2.6287, -2.5005, -2.3722,
       -2.244 , -2.1158, -1.9875, -1.8593, -1.7311, -1.6029, -1.4746,
       -1.3464, -1.2182, -1.0899, -0.9617, -0.8335, -0.7053, -0.577 ,
       -0.4488, -0.3206, -0.1923, -0.0641,  0.0641,  0.1923,  0.3206,
        0.4488,  0.577 ,  0.7053,  0.8335,  0.9617,  1.0899,  1.2182,
        1.3464,  1.4746,  1.6029,  1.7311,  1.8593,  1.9875,  2.1158,
        2.244 ,  2.3722,  2.5005,  2.6287,  2.7569,  2.8851,  3.0134,
        3.1416])

array([4, 6, 8])

In [31]:
# 生成数据网格
x, y = [-1, 0, 1], [-1, 0, 1]
X, Y = np.meshgrid(x, y)
X; Y

array([[-1,  0,  1],
       [-1,  0,  1],
       [-1,  0,  1]])

array([[-1, -1, -1],
       [ 0,  0,  0],
       [ 1,  1,  1]])

### Basic Math functions

In [28]:
# 二维数组纵向替换
A = np.array([[2, -1, 3], [3, 3, -1], [-1, -1, 1]])
b = np.array([-3, 10, -4])

A_1b = np.copy(A)
A_1b
A_1b[:,0]=b
A_1b

array([[ 2, -1,  3],
       [ 3,  3, -1],
       [-1, -1,  1]])

array([[-3, -1,  3],
       [10,  3, -1],
       [-4, -1,  1]])

In [35]:
# 查看数组形状
A.shape 
b.shape

b.shape=(1,3); b # 改变array形状

(3, 3)

(1, 3)

array([[-3, 10, -4]])

In [24]:
# 计算数列差值，也可以用于计算微积分
u8_arr = np.array([1, 2, 4, 7, 0])
np.diff(u8_arr)

array([ 1,  2,  3, -7])

In [25]:
# 计算累加、累乘
sum((1,2,3,4,5))
np.prod((1,2,3,4,5))

15

120

In [5]:
# 数列去重
a=np.array([1,1,2,3,4,4])
b=[1,1,2,3,4,4]
np.unique(a)
np.unique(b)

array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [ ]:
# 计算范数
a
a_norm1 = np.linalg.norm(a,1); a_norm1  # 1范数：绝对值求和
a_norm2 = np.linalg.norm(a,2); a_norm2  # 2范数：欧式距离

In [ ]:
# Calculation function

np.log(4)
